# Generated by Django 5.2.6 on 2026-09-03 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_lowercase_emails'),
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_start', models.DateTimeField(blank=True, help_text='Stored in UTC.', null=True)),
                ('scheduled_end', models.DateTimeField(blank=True, help_text='Stored in UTC.', null=True)),
                ('duration_minutes', models.PositiveSmallIntegerField(default=60)),
                ('timezone', models.CharField(default='UTC', help_text='Timezone the slot is presented in.', max_length=64)),
                ('location_or_link', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('PROPOSED', 'Proposed'), ('CONFIRMED', 'Confirmed'), ('RESCHEDULED', 'Rescheduled'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='PROPOSED', max_length=20)),
                ('booking_token', models.CharField(max_length=64, unique=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('reminder_24h_sent_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_1h_sent_at', models.DateTimeField(blank=True, null=True)),
                ('external_event_ids', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='jobs.application')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='core.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interviews_created', to=settings.AUTH_USER_MODEL)),
                ('interviewers', models.ManyToManyField(blank=True, related_name='interviews', to=settings.AUTH_USER_MODEL)),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interviews', to='jobs.pipelinestage')),
            ],
            options={
                'ordering': ['scheduled_start', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CalendarConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('GOOGLE', 'Google Calendar'), ('OUTLOOK', 'Outlook Calendar')], max_length=20)),
                ('tokens', models.JSONField(blank=True, default=dict)),
                ('enabled', models.BooleanField(default=True)),
                ('account_email', models.EmailField(blank=True, max_length=254)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['provider'],
                'constraints': [models.UniqueConstraint(fields=('user', 'provider'), name='uniq_calendar_connection_per_provider')],
            },
        ),
        migrations.CreateModel(
            name='InterviewerAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start', models.TimeField(help_text='Local start time in the timezone below.')),
                ('end', models.TimeField(help_text='Local end time in the timezone below.')),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviewer_availability', to='core.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviewer_availability', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'interviewer availability',
                'ordering': ['weekday', 'start'],
                'constraints': [models.UniqueConstraint(fields=('company', 'user', 'weekday', 'start', 'end'), name='uniq_availability_window')],
            },
        ),
        migrations.CreateModel(
            name='InterviewSlotProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(help_text='Stored in UTC.')),
                ('end', models.DateTimeField(help_text='Stored in UTC.')),
                ('chosen', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_proposals', to='scheduling.interview')),
            ],
            options={
                'ordering': ['start'],
                'constraints': [models.UniqueConstraint(fields=('interview', 'start'), name='uniq_slot_proposal_per_start')],
            },
        ),
    ]
