# Generated by Django 5.2.6 on 2026-09-03 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_seed_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='features',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
