# Generated by Django 5.2.6 on 2026-09-03 16:30

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_seed_plan_features'),
        ('core', '0004_lowercase_emails'),
        ('jobs', '0005_candidateprofile_share_in_pool'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['price_monthly_inr', 'price_monthly']},
        ),
        migrations.AddField(
            model_name='plan',
            name='ai_credits_monthly',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_seats',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='plan',
            name='per_hire_fee_inr',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='price_monthly_inr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='plan',
            name='price_yearly_inr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='plan',
            name='razorpay_plan_id_monthly',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='plan',
            name='razorpay_plan_id_yearly',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='subscription',
            name='billing_address',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='subscription',
            name='gstin',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='subscription',
            name='interval',
            field=models.CharField(choices=[('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], default='MONTHLY', max_length=10),
        ),
        migrations.AddField(
            model_name='subscription',
            name='past_due_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='provider',
            field=models.CharField(blank=True, choices=[('STRIPE', 'Stripe'), ('RAZORPAY', 'Razorpay')], default='RAZORPAY', max_length=20),
        ),
        migrations.AddField(
            model_name='subscription',
            name='razorpay_customer_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='subscription',
            name='razorpay_subscription_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='subscription',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='code',
            field=models.CharField(choices=[('FREE', 'Free'), ('STARTER', 'Starter'), ('GROWTH', 'Growth'), ('AGENCY', 'Agency'), ('PRO', 'Pro (legacy)')], max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=40, unique=True)),
                ('fy', models.CharField(blank=True, max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gst_rate', models.DecimalField(decimal_places=2, default=Decimal('18.00'), max_digits=5)),
                ('cgst', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sgst', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('igst', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gstin', models.CharField(blank=True, max_length=20)),
                ('place_of_supply', models.CharField(blank=True, max_length=4)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('pdf', models.FileField(blank=True, upload_to='invoices/')),
                ('provider', models.CharField(blank=True, choices=[('STRIPE', 'Stripe'), ('RAZORPAY', 'Razorpay')], max_length=20)),
                ('provider_ref', models.CharField(blank=True, max_length=120)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='core.company')),
            ],
            options={
                'ordering': ['-issued_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PlacementFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('INVOICED', 'Invoiced'), ('PAID', 'Paid'), ('WAIVED', 'Waived')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='placement_fee', to='jobs.application')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placement_fees', to='core.company')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placement_fees', to='billing.invoice')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DunningReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveSmallIntegerField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dunning_reminders', to='billing.subscription')),
            ],
            options={
                'ordering': ['day'],
                'constraints': [models.UniqueConstraint(fields=('subscription', 'day'), name='billing_dunning_unique_day')],
            },
        ),
        migrations.CreateModel(
            name='UsageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('AI_SCREEN', 'AI screening'), ('WHATSAPP_MSG', 'WhatsApp message'), ('VIDEO_MINUTE', 'Video minute')], max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('period_start', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='core.company')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'kind', 'period_start'], name='billing_usa_company_deb3fc_idx')],
            },
        ),
    ]
