# Generated by Django 5.2.6 on 2026-09-03 21:20

from django.db import migrations, models


def seed_counters(apps, schema_editor):
    """Start each FY counter at the highest invoice number already issued."""
    Invoice = apps.get_model("billing", "Invoice")
    InvoiceCounter = apps.get_model("billing", "InvoiceCounter")
    highest = {}
    for number, fy in Invoice.objects.values_list("number", "fy"):
        parts = str(number).split("/")
        if len(parts) != 3:
            continue
        try:
            seq = int(parts[2])
        except ValueError:
            continue
        label = fy or parts[1]
        if not label:
            continue
        highest[label] = max(highest.get(label, 0), seq)
    for fy, seq in highest.items():
        InvoiceCounter.objects.update_or_create(fy=fy, defaults={"last_seq": seq})


def unseed_counters(apps, schema_editor):
    apps.get_model("billing", "InvoiceCounter").objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_ai_extraction_feature'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fy', models.CharField(max_length=10, unique=True)),
                ('last_seq', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['fy'],
            },
        ),
        migrations.CreateModel(
            name='ProcessedWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('STRIPE', 'Stripe'), ('RAZORPAY', 'Razorpay')], max_length=20)),
                ('event_id', models.CharField(max_length=200)),
                ('event_type', models.CharField(blank=True, max_length=100)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-received_at', '-id'],
                'indexes': [models.Index(fields=['provider', 'event_id'], name='billing_pro_provide_a9dbc0_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'event_id'), name='billing_webhook_event_unique')],
            },
        ),
        migrations.RunPython(seed_counters, unseed_counters),
    ]
