# Generated by Django 5.2.6 on 2026-09-04 21:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_integrations_feature'),
        ('core', '0005_invitation_last_used_at_invitation_revoked_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('SUBSCRIPTION', 'Subscription'), ('SUCCESS_FEE', 'Success fee'), ('AI_OVERAGE', 'AI overage'), ('SEAT', 'Seat'), ('BGV', 'Background verification'), ('PLATFORM_FEE', 'Platform fee'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('label', models.CharField(max_length=200)),
                ('amount_inr', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ref', models.CharField(blank=True, max_length=120)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='line_items',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='invoice',
            name='period_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='ai_included',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plan',
            name='ai_overage_inr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='plan',
            name='pricing_model',
            field=models.CharField(choices=[('SEAT', 'Per recruiter seat'), ('FLAT', 'Flat monthly')], default='FLAT', max_length=10),
        ),
        migrations.AddField(
            model_name='plan',
            name='success_fee_inr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='subscription',
            name='grace_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='hard_cap',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usagerecord',
            name='overage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(('period_start__isnull', False)), fields=('company', 'period_start'), name='billing_invoice_unique_period'),
        ),
        migrations.AddField(
            model_name='billingcharge',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_charges', to='core.company'),
        ),
        migrations.AddField(
            model_name='billingcharge',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charges', to='billing.invoice'),
        ),
        migrations.AddIndex(
            model_name='billingcharge',
            index=models.Index(fields=['company', 'occurred_at'], name='billing_bil_company_b5b325_idx'),
        ),
        migrations.AddConstraint(
            model_name='billingcharge',
            constraint=models.UniqueConstraint(condition=models.Q(('ref', ''), _negated=True), fields=('company', 'kind', 'ref'), name='billing_charge_unique_ref'),
        ),
    ]
