# Generated by Django 5.2.6 on 2026-09-06 19:30

from datetime import timedelta

import django.db.models.deletion
from django.db import migrations, models

#: Mirrors ``Invoice.PAYMENT_TERMS_DAYS`` at the time of this migration.
PAYMENT_TERMS_DAYS = 7


def backfill_status(apps, schema_editor):
    """Rows issued before there was a status: paid ones are PAID, the rest ISSUED.

    Unpaid rows also get a due date so the dunning sweep has something to
    compare against instead of ignoring every historical invoice.
    """
    Invoice = apps.get_model("billing", "Invoice")
    Invoice.objects.filter(paid_at__isnull=False).update(status="PAID")
    for invoice in Invoice.objects.filter(paid_at__isnull=True).only("id", "issued_at"):
        Invoice.objects.filter(pk=invoice.pk).update(
            status="ISSUED",
            due_at=(invoice.issued_at + timedelta(days=PAYMENT_TERMS_DAYS)).date(),
        )


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0014_bgv_feature'),
        ('core', '0006_cronstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='due_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued'), ('PAID', 'Paid'), ('VOID', 'Void')], default='ISSUED', max_length=10),
        ),
        migrations.RunPython(backfill_status, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='billingcharge',
            name='kind',
            field=models.CharField(choices=[('SUBSCRIPTION', 'Subscription'), ('SUCCESS_FEE', 'Success fee'), ('AI_OVERAGE', 'AI overage'), ('SEAT', 'Seat'), ('BGV', 'Background verification'), ('PLATFORM_FEE', 'Platform fee'), ('EXCHANGE_FEE', 'Exchange fee'), ('OTHER', 'Other')], default='OTHER', max_length=30),
        ),
        migrations.CreateModel(
            name='PendingCheckout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_id', models.CharField(max_length=120, unique=True)),
                ('interval', models.CharField(choices=[('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], default='MONTHLY', max_length=10)),
                ('amount_inr', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_checkouts', to='core.company')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checkouts', to='billing.invoice')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checkouts', to='billing.plan')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['company', 'remote_id'], name='billing_pen_company_11c5f4_idx')],
            },
        ),
        migrations.CreateModel(
            name='TrialReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_left', models.PositiveSmallIntegerField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trial_reminders', to='billing.subscription')),
            ],
            options={
                'ordering': ['-days_left'],
                'constraints': [models.UniqueConstraint(fields=('subscription', 'days_left'), name='billing_trial_unique_days_left')],
            },
        ),
    ]
