# Generated by Django 5.2.6 on 2026-09-06 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0015_invoice_status_pending_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='trial_warned_days',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
