# Generated by Django 5.2.6 on 2026-09-06 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0016_subscription_trial_warned_days'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrialReminder',
        ),
    ]
