# Generated by Django 5.2.6 on 2026-09-04 21:45

import contracting.validators
import core.tokens
import django.db.models.deletion
import django.utils.timezone
import integrations.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0002_clientaccess_revoked_at'),
        ('core', '0005_invitation_last_used_at_invitation_revoked_at_and_more'),
        ('jobs', '0007_job_salary_blank'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientBillingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gstin', models.CharField(blank=True, max_length=20)),
                ('state_code', models.CharField(blank=True, help_text="Two-digit GST state code of the client's place of supply, e.g. 27.", max_length=2)),
                ('billing_email', models.EmailField(blank=True, max_length=254)),
                ('billing_address', models.TextField(blank=True)),
                ('payment_terms_days', models.PositiveSmallIntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_profile', to='clients.client')),
            ],
            options={
                'ordering': ['client__name'],
            },
        ),
        migrations.CreateModel(
            name='ClientInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=40, unique=True)),
                ('fy', models.CharField(blank=True, max_length=10)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('line_items', models.JSONField(blank=True, default=list)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gst_rate', models.DecimalField(decimal_places=2, default=Decimal('18.00'), max_digits=5)),
                ('cgst', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sgst', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('igst', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gstin', models.CharField(blank=True, max_length=20)),
                ('place_of_supply', models.CharField(blank=True, max_length=2)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue')], default='DRAFT', max_length=8)),
                ('due_at', models.DateField(blank=True, null=True)),
                ('pdf', models.FileField(blank=True, upload_to='contracting/invoices/')),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='clients.client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_invoices', to='core.company')),
            ],
            options={
                'ordering': ['-issued_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=core.tokens.generate_token, max_length=100, unique=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=25)),
                ('pan', models.CharField(blank=True, max_length=10)),
                ('uan', models.CharField(blank=True, max_length=20)),
                ('employee_id', models.CharField(blank=True, help_text='Payroll id used by your HRMS import.', max_length=40)),
                ('bank', integrations.models.EncryptedJSONField(blank=True)),
                ('status', models.CharField(choices=[('ONBOARDING', 'Onboarding'), ('ACTIVE', 'Active'), ('ENDED', 'Ended')], default='ONBOARDING', max_length=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contractor_records', to='jobs.candidateprofile')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contractors', to='core.company')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Engagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_title', models.CharField(max_length=200)),
                ('start', models.DateField()),
                ('end', models.DateField(blank=True, null=True)),
                ('bill_rate_inr', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pay_rate_inr', models.DecimalField(decimal_places=2, max_digits=12)),
                ('rate_unit', models.CharField(choices=[('HOUR', 'Per hour'), ('DAY', 'Per day'), ('MONTH', 'Per month')], default='HOUR', max_length=6)),
                ('tds_percent', models.DecimalField(decimal_places=2, default=Decimal('10'), help_text="Withheld from the contractor's gross (194J/194C).", max_digits=5)),
                ('po_number', models.CharField(blank=True, max_length=60)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('ENDED', 'Ended')], default='ACTIVE', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='engagements', to='clients.client')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagements', to='contracting.contractor')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engagements', to='jobs.job')),
            ],
            options={
                'ordering': ['-start', 'contractor__name'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('PAN', 'PAN card'), ('AADHAAR', 'Aadhaar'), ('OFFER', 'Signed offer'), ('NDA', 'NDA'), ('OTHER', 'Other')], default='OTHER', max_length=10)),
                ('file', models.FileField(upload_to='contracting/documents/', validators=[contracting.validators.validate_document_file])),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='contracting.contractor')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['kind', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientInvoiceCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fy', models.CharField(max_length=10)),
                ('last_seq', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_invoice_counters', to='core.company')),
            ],
            options={
                'ordering': ['company_id', 'fy'],
                'constraints': [models.UniqueConstraint(fields=('company', 'fy'), name='uniq_client_invoice_counter')],
            },
        ),
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='Any date inside the payroll month; stored as the 1st.')),
                ('rows', models.JSONField(blank=True, default=list)),
                ('gross_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tds_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('net_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('csv', models.FileField(blank=True, upload_to='contracting/payroll/')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('FINAL', 'Final')], default='DRAFT', max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_runs', to='core.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-month'],
                'constraints': [models.UniqueConstraint(fields=('company', 'month'), name='uniq_payroll_run_month')],
            },
        ),
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('entries', models.JSONField(blank=True, default=list)),
                ('total_hours', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('INVOICED', 'Invoiced')], default='DRAFT', max_length=10)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('client_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by_access', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='clients.clientaccess')),
                ('approved_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('client_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timesheets', to='contracting.clientinvoice')),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to='contracting.engagement')),
            ],
            options={
                'ordering': ['-period_start'],
                'constraints': [models.UniqueConstraint(fields=('engagement', 'period_start'), name='uniq_timesheet_period')],
            },
        ),
    ]
