# Generated by Django 5.2.6 on 2026-09-05 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientinvoice',
            name='gst_basis_note',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
