# Generated by Django 5.2.6 on 2026-09-03 16:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_lowercase_emails'),
        ('jobs', '0004_job_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareersSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('custom_domain', models.CharField(blank=True, help_text='e.g. careers.example.com — point a CNAME at this app and add the host to ALLOWED_HOSTS.', max_length=253, null=True, unique=True)),
                ('headline', models.CharField(blank=True, max_length=200)),
                ('about', models.TextField(blank=True, help_text="Plain text with blank lines for paragraphs and '- ' for lists.")),
                ('brand_color', models.CharField(default='#2563eb', max_length=7, validators=[django.core.validators.RegexValidator('^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$', 'Enter a hex colour such as #2563eb.')])),
                ('logo', models.ImageField(blank=True, upload_to='careers/logos/')),
                ('hero_image', models.ImageField(blank=True, upload_to='careers/heroes/')),
                ('published', models.BooleanField(default=False)),
                ('seo_title', models.CharField(blank=True, max_length=70)),
                ('seo_description', models.CharField(blank=True, max_length=200)),
                ('show_salary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='careers_site', to='core.company')),
            ],
            options={
                'verbose_name': 'careers site',
            },
        ),
        migrations.CreateModel(
            name='JobDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.CharField(choices=[('LINKEDIN', 'LinkedIn'), ('INDEED', 'Indeed'), ('NAUKRI', 'Naukri'), ('GOOGLE_JOBS', 'Google for Jobs')], max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('FAILED', 'Failed'), ('REMOVED', 'Removed')], default='DRAFT', max_length=10)),
                ('external_id', models.CharField(blank=True, max_length=200)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='jobs.job')),
            ],
            options={
                'ordering': ['board'],
                'constraints': [models.UniqueConstraint(fields=('job', 'board'), name='uniq_distribution_per_board')],
            },
        ),
    ]
