# Generated by Django 5.2.6 on 2026-09-06 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerssite',
            name='list_in_network',
            field=models.BooleanField(default=True, help_text="Also list this site's open roles on the public cross-tenant job board."),
        ),
    ]
