# Generated by Django 5.2.6 on 2026-09-02 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='ai_details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='resume_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='resume_parsed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='resume_text',
            field=models.TextField(blank=True),
        ),
    ]
