# Generated by Django 5.2.6 on 2026-09-03 10:29

import jobs.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_application_ai_details_candidateprofile_resume_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='resume',
            field=models.FileField(blank=True, upload_to='resumes/', validators=[jobs.validators.validate_resume_file]),
        ),
    ]
