# Generated by Django 5.2.6 on 2026-09-04 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_candidateprofile_share_in_pool'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='salary_currency',
            field=models.CharField(default='INR', max_length=8),
        ),
        migrations.AddField(
            model_name='job',
            name='salary_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='salary_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='salary_period',
            field=models.CharField(choices=[('YEAR', 'per year'), ('MONTH', 'per month')], default='YEAR', max_length=10),
        ),
        migrations.AddField(
            model_name='job',
            name='show_salary',
            field=models.BooleanField(default=False, help_text='Publish the salary range on the public job and careers pages.'),
        ),
    ]
