# Generated by Django 5.2.6 on 2026-09-04 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_job_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='salary_currency',
            field=models.CharField(blank=True, default='INR', max_length=8),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary_period',
            field=models.CharField(blank=True, choices=[('YEAR', 'per year'), ('MONTH', 'per month')], default='YEAR', max_length=10),
        ),
    ]
