# Generated by Django 5.2.6 on 2026-09-03 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='manual_scores',
            field=models.JSONField(blank=True, default=dict, help_text='Recruiter-entered {question_id: 0-100} scores for TEXT answers.'),
        ),
        migrations.AddField(
            model_name='attempt',
            name='needs_review',
            field=models.BooleanField(default=False, help_text='A free-text answer could not be graded automatically.'),
        ),
        migrations.AddField(
            model_name='attempt',
            name='pending_review',
            field=models.JSONField(blank=True, default=list, help_text='Question ids still awaiting a manual score.'),
        ),
    ]
