# Generated by Django 5.2.6 on 2026-09-03 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_attempt_manual_scores_attempt_needs_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='source',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('AI', 'AI generated'), ('MARKETPLACE', 'Marketplace')], default='MANUAL', max_length=20),
        ),
    ]
