# Generated by Django 5.2.6 on 2026-09-03 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_company',
            field=models.ForeignKey(blank=True, help_text='Last workspace this user had active; restored on the next login.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.company'),
        ),
    ]
