# Generated by Django 5.2.6 on 2026-09-06 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_invitation_last_used_at_invitation_revoked_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CronState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
