# Generated by Django 5.2.6 on 2026-09-06 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_cronstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='policy_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='policy_version',
            field=models.CharField(blank=True, help_text='web.legal.POLICY_VERSION accepted at signup.', max_length=20),
        ),
    ]
