# Generated by Django 5.2.6 on 2026-09-03 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0003_alter_candidateprofile_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='StageTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_after', models.CharField(max_length=10)),
                ('at', models.DateTimeField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_transitions', to='jobs.application')),
                ('from_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transitions_out', to='jobs.pipelinestage')),
                ('to_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transitions_in', to='jobs.pipelinestage')),
            ],
            options={
                'ordering': ['at', 'id'],
                'indexes': [models.Index(fields=['application', 'at'], name='analytics_s_applica_5f2725_idx'), models.Index(fields=['at'], name='analytics_s_at_295023_idx')],
            },
        ),
    ]
