# Generated by Django 5.2.6 on 2026-09-03 16:30

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_lowercase_emails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reseller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('commission_pct', models.DecimalField(decimal_places=2, default=Decimal('20'), max_digits=5)),
                ('active', models.BooleanField(default=True)),
                ('token', models.CharField(blank=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('SELF_HOSTED', 'Self hosted')], default='SELF_HOSTED', max_length=20)),
                ('key', models.CharField(max_length=255, unique=True)),
                ('seats', models.PositiveIntegerField(default=5)),
                ('expires_at', models.DateTimeField()),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='core.company')),
            ],
            options={
                'ordering': ['-issued_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signed_up_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('first_payment_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral', to='core.company')),
                ('reseller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='partners.reseller')),
            ],
            options={
                'ordering': ['-signed_up_at'],
            },
        ),
        migrations.CreateModel(
            name='WhiteLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(blank=True, max_length=120)),
                ('logo', models.ImageField(blank=True, upload_to='whitelabel/')),
                ('primary_color', models.CharField(blank=True, max_length=20)),
                ('custom_domain', models.CharField(blank=True, max_length=200)),
                ('hide_powered_by', models.BooleanField(default=False)),
                ('email_from_name', models.CharField(blank=True, max_length=120)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='white_label', to='core.company')),
            ],
            options={
                'verbose_name': 'white label',
                'verbose_name_plural': 'white labels',
            },
        ),
        migrations.CreateModel(
            name='CommissionLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_ref', models.CharField(max_length=80)),
                ('amount_inr', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('commission_inr', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_out_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_commissions', to='core.company')),
                ('reseller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='partners.reseller')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('reseller', 'invoice_ref'), name='partners_unique_commission_invoice')],
            },
        ),
    ]
