# Generated by Django 3.2.2 on 2021-05-23 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=50, verbose_name='Employee Name')),
                ('employee_email', models.EmailField(max_length=254, unique=True, verbose_name='Official Email')),
                ('employee_skill', models.CharField(choices=[('Python', 'Python'), ('Java', 'Java')], max_length=50, verbose_name='Skill')),
                ('employee_level', models.CharField(choices=[('L1', 'L1'), ('L2', 'L2'), ('HR', 'HR')], max_length=50, verbose_name='Level')),
                ('employee_username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
            },
        ),
    ]
