# Generated by Django 5.2.6 on 2026-09-05 20:28

import core.tokens
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_invitation_last_used_at_invitation_revoked_at_and_more'),
        ('jobs', '0007_job_salary_blank'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('provider_cost_inr', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_inr', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('checks', models.JSONField(blank=True, default=list)),
                ('turnaround_days', models.PositiveSmallIntegerField(default=5)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['price_inr', 'code'],
            },
        ),
        migrations.CreateModel(
            name='VerificationOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=core.tokens.generate_token, max_length=100, unique=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('price_inr', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('provider_cost_inr', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('checks', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CONSENT_PENDING', 'Awaiting consent'), ('SUBMITTED', 'Submitted'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=16)),
                ('consent_given_at', models.DateTimeField(blank=True, null=True)),
                ('consent_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('consent_name', models.CharField(blank=True, max_length=150)),
                ('provider', models.CharField(blank=True, max_length=40)),
                ('provider_ref', models.CharField(blank=True, max_length=120)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('report_file', models.FileField(blank=True, upload_to='bgv/reports/')),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('charge_ref', models.CharField(blank=True, max_length=100)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_orders', to='jobs.application')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_orders', to='jobs.candidateprofile')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_orders', to='core.company')),
                ('ordered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_orders', to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='bgv.checkpackage')),
            ],
            options={
                'ordering': ['-ordered_at', '-id'],
            },
        ),
    ]
