# Generated by Django 5.2.6 on 2026-09-03 16:30

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_lowercase_emails'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=170, unique=True)),
                ('skill_name', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('price_inr', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('questions', models.JSONField(blank=True, default=list)),
                ('published', models.BooleanField(default=False)),
                ('author', models.CharField(blank=True, max_length=120)),
                ('downloads', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['price_inr', 'title'],
            },
        ),
        migrations.CreateModel(
            name='PackPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_ref', models.CharField(blank=True, max_length=80)),
                ('purchased_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('questions_created', models.PositiveIntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pack_purchases', to='core.company')),
                ('purchased_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='marketplace.questionpack')),
            ],
            options={
                'ordering': ['-purchased_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('company', 'pack'), name='marketplace_unique_company_pack')],
            },
        ),
    ]
