# Generated by Django 3.2.2 on 2021-05-23 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.PositiveBigIntegerField(unique=True, verbose_name='Phone Number')),
                ('dateofbirth', models.DateField(verbose_name='Date of Birth')),
                ('experience', models.DecimalField(decimal_places=2, help_text='Please enter in years', max_digits=5, verbose_name='Experience')),
                ('noticeperiod', models.IntegerField(help_text='Please enter in months', verbose_name='Notice Period')),
                ('source', models.CharField(choices=[('Referral', 'Referral'), ('Job Portal', 'Job Portal'), ('Walk In', 'Walk In')], default='Walk In', max_length=10, verbose_name='Source')),
                ('skill', models.CharField(choices=[('Python', 'Python'), ('Java', 'Java')], default='Python', max_length=10)),
                ('resume', models.FileField(upload_to='documents/', verbose_name='Resume')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('status', models.CharField(choices=[('Selected', 'Selected'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=50, verbose_name='Status')),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Candidate',
                'verbose_name_plural': 'Candidates',
                'ordering': ['-created_at', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CandidateResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_l1', models.CharField(choices=[('Selected', 'Selected'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=50, verbose_name='L1 Status')),
                ('feedback_l1', models.TextField(blank=True, null=True, verbose_name='L1 Feedback')),
                ('status_l2', models.CharField(choices=[('Selected', 'Selected'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=50, verbose_name='L2 Status')),
                ('feedback_l2', models.TextField(blank=True, null=True, verbose_name='L2 Feedback')),
                ('status_hr', models.CharField(choices=[('Selected', 'Selected'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=50, verbose_name='HR Status')),
                ('feedback_hr', models.TextField(blank=True, null=True, verbose_name='HR Feedback')),
                ('candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='candidate.candidate')),
                ('hr_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='employee.employee')),
                ('l1_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='employee.employee')),
                ('l2_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='employee.employee')),
            ],
        ),
    ]
