# Generated by Django 5.0.4 on 2024-04-30 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0004_candidatequestionmodel_candidate_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatequestionmodel',
            name='skill',
            field=models.CharField(choices=[('Python', 'Python'), ('Java', 'Java')], default='Python', max_length=10),
        ),
    ]
