# Generated by Django 5.2.6 on 2026-09-04 21:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_invitation_last_used_at_invitation_revoked_at_and_more'),
        ('jobs', '0007_job_salary_blank'),
        ('talent', '0002_importbatch_items'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('client_name', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('budget_ctc_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('budget_ctc_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('fee_split_pct', models.PositiveSmallIntegerField(default=50)),
                ('visibility', models.CharField(choices=[('PARTNERS', 'Partners only'), ('NETWORK', 'Whole network')], default='PARTNERS', max_length=10)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('FILLED', 'Filled'), ('CLOSED', 'Closed')], default='OPEN', max_length=10)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_requirements', to='core.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchange_requirements_created', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_requirements', to='jobs.job')),
                ('skills', models.ManyToManyField(blank=True, related_name='exchange_requirements', to='jobs.skill')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_snapshot', models.JSONField(blank=True, default=dict)),
                ('email_hash', models.CharField(blank=True, max_length=64)),
                ('resume_file', models.FileField(blank=True, upload_to='exchange/resumes/')),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('SHORTLISTED', 'Shortlisted'), ('INTERVIEWING', 'Interviewing'), ('HIRED', 'Hired'), ('REJECTED', 'Rejected')], default='SUBMITTED', max_length=15)),
                ('revealed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchange_submissions', to='jobs.candidateprofile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchange_submissions_created', to=settings.AUTH_USER_MODEL)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='exchange.exchangerequirement')),
                ('responding_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_submissions', to='core.company')),
                ('talent_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchange_submissions', to='talent.talentprofile')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement_fee_inr', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('split_pct', models.PositiveSmallIntegerField(default=50)),
                ('platform_fee_pct', models.PositiveSmallIntegerField(default=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('INVOICED', 'Invoiced'), ('SETTLED', 'Settled')], default='PENDING', max_length=10)),
                ('disputed', models.BooleanField(default=False)),
                ('dispute_reason', models.TextField(blank=True)),
                ('disputed_at', models.DateTimeField(blank=True, null=True)),
                ('charged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deal', to='exchange.exchangesubmission')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PartnerLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('BLOCKED', 'Blocked')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_links_created', to=settings.AUTH_USER_MODEL)),
                ('from_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_links_sent', to='core.company')),
                ('to_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_links_received', to='core.company')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='exchangerequirement',
            index=models.Index(fields=['status', 'visibility'], name='exchange_ex_status_7cee2d_idx'),
        ),
        migrations.AddIndex(
            model_name='exchangerequirement',
            index=models.Index(fields=['company', 'status'], name='exchange_ex_company_9c1341_idx'),
        ),
        migrations.AddIndex(
            model_name='exchangesubmission',
            index=models.Index(fields=['requirement', 'status'], name='exchange_ex_require_7d56f4_idx'),
        ),
        migrations.AddIndex(
            model_name='exchangesubmission',
            index=models.Index(fields=['responding_company', 'status'], name='exchange_ex_respond_ea555d_idx'),
        ),
        migrations.AddConstraint(
            model_name='exchangesubmission',
            constraint=models.UniqueConstraint(condition=models.Q(('email_hash', ''), _negated=True), fields=('requirement', 'email_hash'), name='exchange_submission_unique_email_per_requirement'),
        ),
        migrations.AddIndex(
            model_name='partnerlink',
            index=models.Index(fields=['status'], name='exchange_pa_status_8c13a2_idx'),
        ),
        migrations.AddConstraint(
            model_name='partnerlink',
            constraint=models.UniqueConstraint(fields=('from_company', 'to_company'), name='exchange_partner_unique_pair'),
        ),
        migrations.AddConstraint(
            model_name='partnerlink',
            constraint=models.CheckConstraint(condition=models.Q(('from_company', models.F('to_company')), _negated=True), name='exchange_partner_not_self'),
        ),
    ]
