# Generated by Django 5.2.6 on 2026-09-06 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0007_job_salary_blank'),
        ('sources', '0002_seed_sources'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeekerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_roles', models.JSONField(blank=True, default=list)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('min_budget_inr', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('remote_only', models.BooleanField(default=False)),
                ('is_pro', models.BooleanField(default=False)),
                ('sends_this_month', models.PositiveIntegerField(default=0)),
                ('month_key', models.CharField(blank=True, max_length=7)),
                ('mailbox_kind', models.CharField(choices=[('NONE', 'Not connected'), ('GMAIL', 'Gmail'), ('SMTP', 'SMTP')], default='NONE', max_length=8)),
                ('mailbox_config', models.TextField(blank=True)),
                ('mailbox_email', models.EmailField(blank=True, max_length=254)),
                ('upgrade_requested_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seeker_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SavedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SAVED', 'Saved'), ('APPLIED', 'Applied'), ('CONTACTED', 'Contacted'), ('REPLIED', 'Replied'), ('REJECTED', 'Rejected'), ('ARCHIVED', 'Archived')], default='SAVED', max_length=12)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_seekers', to='jobs.job')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='sources.lead')),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_items', to='seeker.seekerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Outreach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=300)),
                ('body', models.TextField()),
                ('resume_attached', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='DRAFT', max_length=8)),
                ('provider_message_id', models.CharField(blank=True, max_length=200)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('saved_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outreach', to='seeker.saveditem')),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outreach', to='seeker.seekerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='saveditem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('job__isnull', True), ('lead__isnull', False)), models.Q(('job__isnull', False), ('lead__isnull', True)), _connector='OR'), name='seeker_saveditem_exactly_one_target'),
        ),
        migrations.AddConstraint(
            model_name='saveditem',
            constraint=models.UniqueConstraint(fields=('seeker', 'lead'), name='seeker_saveditem_unique_lead'),
        ),
        migrations.AddConstraint(
            model_name='saveditem',
            constraint=models.UniqueConstraint(fields=('seeker', 'job'), name='seeker_saveditem_unique_job'),
        ),
    ]
