# Generated by Django 5.2.6 on 2026-09-03 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_lowercase_emails'),
        ('jobs', '0002_application_ai_details_candidateprofile_resume_hash_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to='talent/imports/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('DONE', 'Done'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('total', models.PositiveIntegerField(default=0)),
                ('created', models.PositiveIntegerField(default=0)),
                ('updated', models.PositiveIntegerField(default=0)),
                ('skipped', models.PositiveIntegerField(default=0)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talent_imports', to='core.company')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='talent_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'import batches',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TalentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('headline', models.CharField(blank=True, max_length=200)),
                ('experience_years', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('current_company', models.CharField(blank=True, max_length=150)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('resume', models.FileField(blank=True, upload_to='talent/')),
                ('resume_text', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('source', models.CharField(choices=[('MANUAL', 'Manual'), ('IMPORT', 'Import'), ('APPLICANT', 'Applicant'), ('REFERRAL', 'Referral')], default='MANUAL', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('last_contacted', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talent_profiles', to='core.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sourced_talent', to=settings.AUTH_USER_MODEL)),
                ('linked_candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='talent_profiles', to='jobs.candidateprofile')),
                ('skills', models.ManyToManyField(blank=True, related_name='talent_profiles', to='jobs.skill')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
                'indexes': [models.Index(fields=['company', 'email'], name='talent_tale_company_3686b9_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'email'), name='talent_unique_company_email')],
            },
        ),
    ]
