# Generated by Django 5.2.6 on 2026-09-03 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='importbatch',
            name='items',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
