# Generated by Django 3.2.2 on 2021-05-23 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateresult',
            name='hr_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='candidateresult',
            name='l1_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='candidateresult',
            name='l2_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='employee.employee'),
        ),
    ]
