# Generated by Django 3.2.2 on 2021-05-15 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='experience',
            field=models.DecimalField(decimal_places=10, help_text='Please enter in years', max_digits=10, verbose_name='Experience'),
        ),
    ]
