# Generated by Django 3.2.2 on 2021-05-15 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0002_alter_candidate_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='experience',
            field=models.DecimalField(decimal_places=2, help_text='Please enter in years', max_digits=5, verbose_name='Experience'),
        ),
    ]
