# Generated by Django 3.2.2 on 2021-05-15 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0003_alter_candidate_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('Selected', 'Selected'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=50, verbose_name='Status'),
        ),
    ]
