# Generated by Django 5.0.4 on 2024-04-30 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0003_candidateresult_hr_at_candidateresult_l1_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateQuestionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, null=True)),
                ('option1', models.CharField(max_length=200, null=True)),
                ('option2', models.CharField(max_length=200, null=True)),
                ('option3', models.CharField(max_length=200, null=True)),
                ('option4', models.CharField(max_length=200, null=True)),
                ('answer', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='candidate',
            name='score',
            field=models.IntegerField(null=True, verbose_name='Score'),
        ),
        migrations.CreateModel(
            name='CandidateResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.CharField(max_length=200, null=True)),
                ('correct', models.BooleanField(null=True)),
                ('candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='candidate.candidate')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate.candidatequestionmodel')),
            ],
        ),
    ]
