# Generated by Django 5.2.6 on 2026-09-04 16:02

import django.db.models.deletion
import integrations.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_invitation_last_used_at_invitation_revoked_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectorConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('KEKA', 'Keka HRMS'), ('ZOHO_PEOPLE', 'Zoho People'), ('GREYTHR', 'greytHR'), ('BACKGROUND_CHECK', 'Background check')], max_length=30)),
                ('settings', integrations.models.EncryptedJSONField(blank=True)),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connector_configs', to='core.company')),
            ],
            options={
                'verbose_name': 'connector configuration',
                'ordering': ['kind'],
            },
        ),
        migrations.CreateModel(
            name='ConnectorRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('KEKA', 'Keka HRMS'), ('ZOHO_PEOPLE', 'Zoho People'), ('GREYTHR', 'greytHR'), ('BACKGROUND_CHECK', 'Background check')], max_length=30)),
                ('status', models.CharField(choices=[('OK', 'Ok'), ('SKIPPED', 'Skipped'), ('ERROR', 'Error')], default='OK', max_length=10)),
                ('detail', models.TextField(blank=True)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='integrations.connectorconfig')),
            ],
            options={
                'verbose_name': 'connector run',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='OutboundWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('url', models.URLField(max_length=500)),
                ('secret', models.CharField(blank=True, help_text='Shared secret used to sign deliveries; generated when blank.', max_length=64)),
                ('events', models.JSONField(blank=True, default=list, help_text='Event names to send. An empty list means every event.')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='core.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_webhooks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'outbound webhook',
                'ordering': ['name', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('application.created', 'Application created'), ('application.stage_changed', 'Application moved stage'), ('application.rejected', 'Application rejected'), ('application.hired', 'Candidate hired'), ('offer.accepted', 'Offer accepted'), ('interview.confirmed', 'Interview confirmed'), ('assessment.submitted', 'Assessment submitted')], max_length=60)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('response_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('webhook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='integrations.outboundwebhook')),
            ],
            options={
                'verbose_name': 'webhook delivery',
                'verbose_name_plural': 'webhook deliveries',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='connectorconfig',
            constraint=models.UniqueConstraint(fields=('company', 'kind'), name='unique_connector_per_company'),
        ),
        migrations.AddIndex(
            model_name='webhookdelivery',
            index=models.Index(fields=['status', 'next_attempt_at'], name='integration_status_d4f89b_idx'),
        ),
    ]
