# Generated by Django 5.2.6 on 2026-09-06 12:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('API', 'API'), ('RSS', 'RSS'), ('ATS', 'ATS board')], default='API', max_length=8)),
                ('enabled', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(blank=True, max_length=16)),
                ('last_error', models.TextField(blank=True)),
                ('items_seen', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=128)),
                ('kind', models.CharField(choices=[('JOB', 'Job'), ('FREELANCE', 'Freelance'), ('GIG', 'Gig')], default='JOB', max_length=12)),
                ('title', models.CharField(max_length=300)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('snippet', models.TextField(blank=True)),
                ('url', models.URLField(max_length=600)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('remote', models.BooleanField(default=False)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(blank=True, max_length=8)),
                ('budget_text', models.CharField(blank=True, max_length=120)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('content_hash', models.CharField(max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='sources.source')),
            ],
            options={
                'ordering': ['-posted_at', '-fetched_at'],
                'indexes': [models.Index(fields=['kind', '-posted_at'], name='sources_lea_kind_950b82_idx'), models.Index(fields=['is_active', '-posted_at'], name='sources_lea_is_acti_322e35_idx')],
            },
        ),
    ]
