# Generated by Django 5.2.6 on 2026-09-03 16:26

import django.db.models.deletion
import video.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_lowercase_emails'),
        ('jobs', '0004_job_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('think_seconds', models.PositiveIntegerField(default=30, help_text='Seconds the candidate gets to prepare before recording starts.')),
                ('answer_seconds', models.PositiveIntegerField(default=120, help_text='Maximum recording length in seconds.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_questions', to='core.company')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VideoScreen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('deadline_days', models.PositiveIntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_screens', to='jobs.job')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_screens', to='jobs.pipelinestage')),
            ],
            options={
                'ordering': ['job_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VideoInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In progress'), ('SUBMITTED', 'Submitted'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_invites', to='jobs.application')),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='video.videoscreen')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('application', 'screen')},
            },
        ),
        migrations.CreateModel(
            name='VideoScreenQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenquestion_links', to='video.videoquestion')),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_links', to='video.videoscreen')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('screen', 'question')},
            },
        ),
        migrations.AddField(
            model_name='videoscreen',
            name='questions',
            field=models.ManyToManyField(related_name='screens', through='video.VideoScreenQuestion', to='video.videoquestion'),
        ),
        migrations.CreateModel(
            name='VideoResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='video/%Y/%m/', validators=[video.models.validate_response_file])),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('mime', models.CharField(blank=True, max_length=100)),
                ('transcript', models.TextField(blank=True)),
                ('ai_summary', models.TextField(blank=True)),
                ('ai_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed')], default='UPLOADED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('invite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='video.videoinvite')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='video.videoquestion')),
            ],
            options={
                'ordering': ['question__order', 'id'],
                'unique_together': {('invite', 'question')},
            },
        ),
    ]
