# Generated by Django 5.2.6 on 2026-09-30 00:14

import core.storage
import video.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoresponse',
            name='file',
            field=models.FileField(storage=core.storage.CloudinaryVideoStorage(), upload_to='video/%Y/%m/', validators=[video.models.validate_response_file]),
        ),
    ]
