# Generated by Django 5.2.6 on 2026-09-03 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatechanneloptout',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('email_marketing', 'Non-essential email')], max_length=20),
        ),
    ]
